# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Getting flutter version"
          command: flutter doctor
      - run:
          name: "test the app"
          command: flutter test
      - run:
          name: "build apk"
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

workflows:
  build-workflow:
    jobs:
      - build
