version: 2.1
orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Getting flutter version"
          command: flutter doctor
      - run:
          name: "building flutter app"
          command: flutter build

  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "testing flutter app"
          command: flutter test

  generate-apk:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "build apk"
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

workflows:
  build-test-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
      
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup  
      - generate-apk:
          requires:
            - test
          filters:
            branches:
              only:
                - circleci-project-setup  
       
  
